# Generated by Django 4.2.23 on 2025-08-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_dietary_preferences',
            field=models.BooleanField(default=True, help_text='Allow other users to see your dietary preferences'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Allow other users to see your email address'),
        ),
    ]
