# Generated by Django 4.2.23 on 2025-08-01 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_comment_parent_comment'),
        ('accounts', '0002_userprofile_show_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, help_text='Select your dietary restrictions and preferences', limit_choices_to={'tag_type': 'dietary'}, related_name='users_with_dietary_preference', to='recipes.tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, help_text='Select your favorite cuisines', limit_choices_to={'tag_type': 'cuisine'}, related_name='users_who_favorite', to='recipes.tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_difficulty',
            field=models.ForeignKey(blank=True, help_text='Your preferred recipe difficulty level', limit_choices_to={'tag_type': 'difficulty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_preferred_difficulty', to='recipes.tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.TextField(blank=True, help_text='Legacy field - use dietary_tags instead'),
        ),
    ]
