# Generated by Django 4.2.23 on 2025-07-26 18:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload recipe image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload step image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste image URL'),
        ),
    ]
