# Generated by Django 4.2.23 on 2025-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_recipe_slug_recipestep_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dietary_flags',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, help_text='Dietary restriction tags', limit_choices_to={'tag_type': 'dietary'}, to='recipes.tag'),
        ),
    ]
