# Generated by Django 4.2.23 on 2025-08-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='Reply to another comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.comment'),
        ),
    ]
