# Generated by Django 4.2.23 on 2025-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='grams_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate grams per unit for nutritional calculations', max_digits=10, null=True),
        ),
    ]
