# Generated by Django 4.2.23 on 2025-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipelike_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Comments must be approved by admin before appearing on site'),
        ),
    ]
