# Generated by Django 4.2.23 on 2025-08-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
    ]
